// Code generated by the Encore v1.49.1 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/
import type { CookieWithOptions } from "encore.dev/api";

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = "http://localhost:4000"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}-leave-management-system-99ki.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

const BROWSER = typeof globalThis === "object" && ("window" in globalThis);

/**
 * Client is an API client for the leave-management-system-99ki Encore application.
 */
export class Client {
    public readonly leave: leave.ServiceClient
    public readonly storage: storage.ServiceClient
    private readonly options: ClientOptions
    private readonly target: string


    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions) {
        this.target = target
        this.options = options ?? {}
        const base = new BaseClient(this.target, this.options)
        this.leave = new leave.ServiceClient(base)
        this.storage = new storage.ServiceClient(base)
    }

    /**
     * Creates a new Encore client with the given client options set.
     *
     * @param options Client options to set. They are merged with existing options.
     **/
    public with(options: ClientOptions): Client {
        return new Client(this.target, {
            ...this.options,
            ...options,
        })
    }
}

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import {
    createAbsenceConversionRequest as api_leave_absence_management_createAbsenceConversionRequest,
    createAbsenceRecord as api_leave_absence_management_createAbsenceRecord,
    listAbsenceConversionRequests as api_leave_absence_management_listAbsenceConversionRequests,
    listAbsenceRecords as api_leave_absence_management_listAbsenceRecords,
    updateAbsenceConversionStatus as api_leave_absence_management_updateAbsenceConversionStatus
} from "~backend/leave/absence_management";
import {
    createAdminUser as api_leave_admin_createAdminUser,
    createInitialAdmin as api_leave_admin_createInitialAdmin,
    getAdminStats as api_leave_admin_getAdminStats,
    getSystemHealth as api_leave_admin_getSystemHealth,
    updateUserRole as api_leave_admin_updateUserRole
} from "~backend/leave/admin";
import { login as api_leave_auth_login } from "~backend/leave/auth";
import {
    createDocument as api_leave_documents_createDocument,
    deleteDocument as api_leave_documents_deleteDocument,
    getExpiringDocuments as api_leave_documents_getExpiringDocuments,
    listDocuments as api_leave_documents_listDocuments,
    updateDocument as api_leave_documents_updateDocument
} from "~backend/leave/documents";
import {
    createEmployee as api_leave_employees_createEmployee,
    getEmployee as api_leave_employees_getEmployee,
    listEmployees as api_leave_employees_listEmployees,
    updateEmployeeProfile as api_leave_employees_updateEmployeeProfile
} from "~backend/leave/employees";
import {
    getEmployeeBalances as api_leave_leave_balances_getEmployeeBalances,
    updateBalance as api_leave_leave_balances_updateBalance
} from "~backend/leave/leave_balances";
import {
    createLeaveRequest as api_leave_leave_requests_createLeaveRequest,
    listLeaveRequests as api_leave_leave_requests_listLeaveRequests,
    updateLeaveRequestStatus as api_leave_leave_requests_updateLeaveRequestStatus
} from "~backend/leave/leave_requests";
import { listLeaveTypes as api_leave_leave_types_listLeaveTypes } from "~backend/leave/leave_types";
import {
    checkExpiringDocuments as api_leave_notifications_checkExpiringDocuments,
    sendExpiryNotification as api_leave_notifications_sendExpiryNotification
} from "~backend/leave/notifications";
import {
    getLeaveUsageReport as api_leave_reports_getLeaveUsageReport,
    getPendingRequestsSummary as api_leave_reports_getPendingRequestsSummary
} from "~backend/leave/reports";
import {
    getUser as api_leave_supabase_sync_getUser,
    syncUser as api_leave_supabase_sync_syncUser
} from "~backend/leave/supabase_sync";
import {
    testAuth as api_leave_test_auth_testAuth,
    testNoAuth as api_leave_test_auth_testNoAuth
} from "~backend/leave/test_auth";

export namespace leave {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.checkExpiringDocuments = this.checkExpiringDocuments.bind(this)
            this.createAbsenceConversionRequest = this.createAbsenceConversionRequest.bind(this)
            this.createAbsenceRecord = this.createAbsenceRecord.bind(this)
            this.createAdminUser = this.createAdminUser.bind(this)
            this.createDocument = this.createDocument.bind(this)
            this.createEmployee = this.createEmployee.bind(this)
            this.createInitialAdmin = this.createInitialAdmin.bind(this)
            this.createLeaveRequest = this.createLeaveRequest.bind(this)
            this.deleteDocument = this.deleteDocument.bind(this)
            this.getAdminStats = this.getAdminStats.bind(this)
            this.getEmployee = this.getEmployee.bind(this)
            this.getEmployeeBalances = this.getEmployeeBalances.bind(this)
            this.getExpiringDocuments = this.getExpiringDocuments.bind(this)
            this.getLeaveUsageReport = this.getLeaveUsageReport.bind(this)
            this.getPendingRequestsSummary = this.getPendingRequestsSummary.bind(this)
            this.getSystemHealth = this.getSystemHealth.bind(this)
            this.getUser = this.getUser.bind(this)
            this.listAbsenceConversionRequests = this.listAbsenceConversionRequests.bind(this)
            this.listAbsenceRecords = this.listAbsenceRecords.bind(this)
            this.listDocuments = this.listDocuments.bind(this)
            this.listEmployees = this.listEmployees.bind(this)
            this.listLeaveRequests = this.listLeaveRequests.bind(this)
            this.listLeaveTypes = this.listLeaveTypes.bind(this)
            this.login = this.login.bind(this)
            this.sendExpiryNotification = this.sendExpiryNotification.bind(this)
            this.syncUser = this.syncUser.bind(this)
            this.testAuth = this.testAuth.bind(this)
            this.testNoAuth = this.testNoAuth.bind(this)
            this.updateAbsenceConversionStatus = this.updateAbsenceConversionStatus.bind(this)
            this.updateBalance = this.updateBalance.bind(this)
            this.updateDocument = this.updateDocument.bind(this)
            this.updateEmployeeProfile = this.updateEmployeeProfile.bind(this)
            this.updateLeaveRequestStatus = this.updateLeaveRequestStatus.bind(this)
            this.updateUserRole = this.updateUserRole.bind(this)
        }

        /**
         * Checks for expiring documents and sends notifications.
         */
        public async checkExpiringDocuments(): Promise<ResponseType<typeof api_leave_notifications_checkExpiringDocuments>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/notifications/check-expiring`, {method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_leave_notifications_checkExpiringDocuments>
        }

        /**
         * Creates a new absence conversion request.
         */
        public async createAbsenceConversionRequest(params: RequestType<typeof api_leave_absence_management_createAbsenceConversionRequest>): Promise<ResponseType<typeof api_leave_absence_management_createAbsenceConversionRequest>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/absence-conversion-requests`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_leave_absence_management_createAbsenceConversionRequest>
        }

        /**
         * Creates a new absence record (HR only).
         */
        public async createAbsenceRecord(params: RequestType<typeof api_leave_absence_management_createAbsenceRecord>): Promise<ResponseType<typeof api_leave_absence_management_createAbsenceRecord>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/absence-records`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_leave_absence_management_createAbsenceRecord>
        }

        /**
         * Creates additional admin users - requires existing HR role
         */
        public async createAdminUser(params: RequestType<typeof api_leave_admin_createAdminUser>): Promise<ResponseType<typeof api_leave_admin_createAdminUser>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/admin/create`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_leave_admin_createAdminUser>
        }

        /**
         * Creates a new company document record.
         */
        public async createDocument(params: RequestType<typeof api_leave_documents_createDocument>): Promise<ResponseType<typeof api_leave_documents_createDocument>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/company-documents`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_leave_documents_createDocument>
        }

        /**
         * Creates a new employee and initializes their leave balances.
         */
        public async createEmployee(params: RequestType<typeof api_leave_employees_createEmployee>): Promise<ResponseType<typeof api_leave_employees_createEmployee>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/employees`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_leave_employees_createEmployee>
        }

        /**
         * Creates the initial admin user - requires secret key
         * This endpoint should only be used once during system setup
         */
        public async createInitialAdmin(params: RequestType<typeof api_leave_admin_createInitialAdmin>): Promise<ResponseType<typeof api_leave_admin_createInitialAdmin>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/admin/create-initial`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_leave_admin_createInitialAdmin>
        }

        /**
         * Creates a new leave request.
         */
        public async createLeaveRequest(params: RequestType<typeof api_leave_leave_requests_createLeaveRequest>): Promise<ResponseType<typeof api_leave_leave_requests_createLeaveRequest>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/leave-requests`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_leave_leave_requests_createLeaveRequest>
        }

        /**
         * Deletes a company document.
         */
        public async deleteDocument(params: { id: number }): Promise<void> {
            await this.baseClient.callTypedAPI(`/company-documents/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
        }

        /**
         * Gets admin dashboard statistics
         */
        public async getAdminStats(): Promise<ResponseType<typeof api_leave_admin_getAdminStats>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/admin/stats`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_leave_admin_getAdminStats>
        }

        /**
         * Retrieves a specific employee by ID.
         */
        public async getEmployee(params: { id: number }): Promise<ResponseType<typeof api_leave_employees_getEmployee>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/employees/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_leave_employees_getEmployee>
        }

        /**
         * Retrieves leave balances for a specific employee.
         */
        public async getEmployeeBalances(params: { employeeId: number }): Promise<ResponseType<typeof api_leave_leave_balances_getEmployeeBalances>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/employees/${encodeURIComponent(params.employeeId)}/balances`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_leave_leave_balances_getEmployeeBalances>
        }

        /**
         * Retrieves documents that are expiring within the next 30 days.
         */
        public async getExpiringDocuments(): Promise<ResponseType<typeof api_leave_documents_getExpiringDocuments>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/company-documents/expiring`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_leave_documents_getExpiringDocuments>
        }

        /**
         * Generates a comprehensive leave usage report for HR.
         */
        public async getLeaveUsageReport(params: RequestType<typeof api_leave_reports_getLeaveUsageReport>): Promise<ResponseType<typeof api_leave_reports_getLeaveUsageReport>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                department: params.department,
                year:       params.year === undefined ? undefined : String(params.year),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/reports/leave-usage`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_leave_reports_getLeaveUsageReport>
        }

        /**
         * Generates a summary of pending leave requests for managers and HR.
         */
        public async getPendingRequestsSummary(): Promise<ResponseType<typeof api_leave_reports_getPendingRequestsSummary>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/reports/pending-requests`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_leave_reports_getPendingRequestsSummary>
        }

        /**
         * System health check for administrators
         */
        public async getSystemHealth(): Promise<ResponseType<typeof api_leave_admin_getSystemHealth>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/admin/health`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_leave_admin_getSystemHealth>
        }

        /**
         * Gets user data by Supabase user ID
         */
        public async getUser(params: { supabaseUserId: string }): Promise<ResponseType<typeof api_leave_supabase_sync_getUser>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/auth/user/${encodeURIComponent(params.supabaseUserId)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_leave_supabase_sync_getUser>
        }

        /**
         * Retrieves absence conversion requests with optional filtering.
         */
        public async listAbsenceConversionRequests(params: RequestType<typeof api_leave_absence_management_listAbsenceConversionRequests>): Promise<ResponseType<typeof api_leave_absence_management_listAbsenceConversionRequests>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                employeeId: params.employeeId === undefined ? undefined : String(params.employeeId),
                managerId:  params.managerId === undefined ? undefined : String(params.managerId),
                status:     params.status,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/absence-conversion-requests`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_leave_absence_management_listAbsenceConversionRequests>
        }

        /**
         * Retrieves absence records with optional filtering.
         */
        public async listAbsenceRecords(params: RequestType<typeof api_leave_absence_management_listAbsenceRecords>): Promise<ResponseType<typeof api_leave_absence_management_listAbsenceRecords>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                employeeId: params.employeeId === undefined ? undefined : String(params.employeeId),
                status:     params.status,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/absence-records`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_leave_absence_management_listAbsenceRecords>
        }

        /**
         * Retrieves all company documents.
         */
        public async listDocuments(params: RequestType<typeof api_leave_documents_listDocuments>): Promise<ResponseType<typeof api_leave_documents_listDocuments>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                documentType: params.documentType,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/company-documents`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_leave_documents_listDocuments>
        }

        /**
         * Retrieves all employees.
         */
        public async listEmployees(): Promise<ResponseType<typeof api_leave_employees_listEmployees>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/employees`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_leave_employees_listEmployees>
        }

        /**
         * Retrieves leave requests with optional filtering.
         */
        public async listLeaveRequests(params: RequestType<typeof api_leave_leave_requests_listLeaveRequests>): Promise<ResponseType<typeof api_leave_leave_requests_listLeaveRequests>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                employeeId: params.employeeId === undefined ? undefined : String(params.employeeId),
                managerId:  params.managerId === undefined ? undefined : String(params.managerId),
                status:     params.status,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/leave-requests`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_leave_leave_requests_listLeaveRequests>
        }

        /**
         * Retrieves all leave types.
         */
        public async listLeaveTypes(): Promise<ResponseType<typeof api_leave_leave_types_listLeaveTypes>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/leave-types`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_leave_leave_types_listLeaveTypes>
        }

        public async login(params: RequestType<typeof api_leave_auth_login>): Promise<ResponseType<typeof api_leave_auth_login>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/auth/login`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_leave_auth_login>
        }

        /**
         * Sends an email notification for document expiry.
         */
        public async sendExpiryNotification(params: RequestType<typeof api_leave_notifications_sendExpiryNotification>): Promise<void> {
            await this.baseClient.callTypedAPI(`/notifications/document-expiry`, {method: "POST", body: JSON.stringify(params)})
        }

        /**
         * Synchronizes a user from Supabase to the internal database
         */
        public async syncUser(params: RequestType<typeof api_leave_supabase_sync_syncUser>): Promise<ResponseType<typeof api_leave_supabase_sync_syncUser>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/auth/sync-user`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_leave_supabase_sync_syncUser>
        }

        public async testAuth(): Promise<ResponseType<typeof api_leave_test_auth_testAuth>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/test/auth`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_leave_test_auth_testAuth>
        }

        /**
         * Test endpoint without auth
         */
        public async testNoAuth(): Promise<ResponseType<typeof api_leave_test_auth_testNoAuth>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/test/no-auth`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_leave_test_auth_testNoAuth>
        }

        /**
         * Updates the status of an absence conversion request (approve/reject).
         */
        public async updateAbsenceConversionStatus(params: RequestType<typeof api_leave_absence_management_updateAbsenceConversionStatus>): Promise<ResponseType<typeof api_leave_absence_management_updateAbsenceConversionStatus>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                approvedBy:      params.approvedBy,
                managerComments: params.managerComments,
                status:          params.status,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/absence-conversion-requests/${encodeURIComponent(params.id)}/status`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_leave_absence_management_updateAbsenceConversionStatus>
        }

        /**
         * Updates an employee's leave balance (HR only).
         */
        public async updateBalance(params: RequestType<typeof api_leave_leave_balances_updateBalance>): Promise<ResponseType<typeof api_leave_leave_balances_updateBalance>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/balances`, {method: "PUT", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_leave_leave_balances_updateBalance>
        }

        /**
         * Updates a company document.
         */
        public async updateDocument(params: RequestType<typeof api_leave_documents_updateDocument>): Promise<ResponseType<typeof api_leave_documents_updateDocument>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                description: params.description,
                expiryDate:  params.expiryDate,
                name:        params.name,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/company-documents/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_leave_documents_updateDocument>
        }

        /**
         * Updates an employee's profile information.
         */
        public async updateEmployeeProfile(params: RequestType<typeof api_leave_employees_updateEmployeeProfile>): Promise<ResponseType<typeof api_leave_employees_updateEmployeeProfile>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                department:      params.department,
                name:            params.name,
                profileImageUrl: params.profileImageUrl,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/employees/${encodeURIComponent(params.id)}/profile`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_leave_employees_updateEmployeeProfile>
        }

        /**
         * Updates the status of a leave request (approve/reject).
         */
        public async updateLeaveRequestStatus(params: RequestType<typeof api_leave_leave_requests_updateLeaveRequestStatus>): Promise<ResponseType<typeof api_leave_leave_requests_updateLeaveRequestStatus>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                approvedBy:      params.approvedBy,
                managerComments: params.managerComments,
                status:          params.status,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/leave-requests/${encodeURIComponent(params.id)}/status`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_leave_leave_requests_updateLeaveRequestStatus>
        }

        /**
         * Updates user role - HR only operation
         */
        public async updateUserRole(params: RequestType<typeof api_leave_admin_updateUserRole>): Promise<ResponseType<typeof api_leave_admin_updateUserRole>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/admin/update-role`, {method: "PUT", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_leave_admin_updateUserRole>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import {
    getCompanyDocument as api_storage_company_documents_getCompanyDocument,
    uploadCompanyDocument as api_storage_company_documents_uploadCompanyDocument
} from "~backend/storage/company_documents";
import {
    getDocument as api_storage_documents_getDocument,
    uploadDocument as api_storage_documents_uploadDocument
} from "~backend/storage/documents";
import { uploadProfileImage as api_storage_profile_images_uploadProfileImage } from "~backend/storage/profile_images";

export namespace storage {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.getCompanyDocument = this.getCompanyDocument.bind(this)
            this.getDocument = this.getDocument.bind(this)
            this.uploadCompanyDocument = this.uploadCompanyDocument.bind(this)
            this.uploadDocument = this.uploadDocument.bind(this)
            this.uploadProfileImage = this.uploadProfileImage.bind(this)
        }

        /**
         * Generates a download URL for a company document.
         */
        public async getCompanyDocument(params: { filePath: string }): Promise<ResponseType<typeof api_storage_company_documents_getCompanyDocument>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/company-documents/file/${encodeURIComponent(params.filePath)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_storage_company_documents_getCompanyDocument>
        }

        /**
         * Generates a download URL for a document.
         */
        public async getDocument(params: { documentId: string }): Promise<ResponseType<typeof api_storage_documents_getDocument>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/leave-documents/${encodeURIComponent(params.documentId)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_storage_documents_getDocument>
        }

        /**
         * Uploads a company document to object storage.
         */
        public async uploadCompanyDocument(params: RequestType<typeof api_storage_company_documents_uploadCompanyDocument>): Promise<ResponseType<typeof api_storage_company_documents_uploadCompanyDocument>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/company-documents/upload`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_storage_company_documents_uploadCompanyDocument>
        }

        /**
         * Uploads a supporting document for a leave request.
         */
        public async uploadDocument(params: RequestType<typeof api_storage_documents_uploadDocument>): Promise<ResponseType<typeof api_storage_documents_uploadDocument>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/leave-documents/upload`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_storage_documents_uploadDocument>
        }

        /**
         * Uploads a profile image for an employee.
         */
        public async uploadProfileImage(params: RequestType<typeof api_storage_profile_images_uploadProfileImage>): Promise<ResponseType<typeof api_storage_profile_images_uploadProfileImage>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/profile-images/upload`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_storage_profile_images_uploadProfileImage>
        }
    }
}


type PickMethods<Type> = Omit<CallParameters, "method"> & { method?: Type };

// Helper type to omit all fields that are cookies.
type OmitCookie<T> = {
  [K in keyof T as T[K] extends CookieWithOptions<any> ? never : K]: T[K];
};

type RequestType<Type extends (...args: any[]) => any> =
  Parameters<Type> extends [infer H, ...any[]]
    ? OmitCookie<H>
    : void;

type ResponseType<Type extends (...args: any[]) => any> = OmitCookie<Awaited<ReturnType<Type>>>;

function dateReviver(key: string, value: any): any {
  if (
    typeof value === "string" &&
    value.length >= 10 &&
    value.charCodeAt(0) >= 48 && // '0'
    value.charCodeAt(0) <= 57 // '9'
  ) {
    const parsedDate = new Date(value);
    if (!isNaN(parsedDate.getTime())) {
      return parsedDate;
    }
  }
  return value;
}


function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ?  parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}

import {
  StreamInOutHandlerFn,
  StreamInHandlerFn,
  StreamOutHandlerFn,
} from "encore.dev/api";

type StreamRequest<Type> = Type extends
  | StreamInOutHandlerFn<any, infer Req, any>
  | StreamInHandlerFn<any, infer Req, any>
  | StreamOutHandlerFn<any, any>
  ? Req
  : never;

type StreamResponse<Type> = Type extends
  | StreamInOutHandlerFn<any, any, infer Resp>
  | StreamInHandlerFn<any, any, infer Resp>
  | StreamOutHandlerFn<any, infer Resp>
  ? Resp
  : never;


function encodeWebSocketHeaders(headers: Record<string, string>) {
    // url safe, no pad
    const base64encoded = btoa(JSON.stringify(headers))
      .replaceAll("=", "")
      .replaceAll("+", "-")
      .replaceAll("/", "_");
    return "encore.dev.headers." + base64encoded;
}

class WebSocketConnection {
    public ws: WebSocket;

    private hasUpdateHandlers: (() => void)[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        let protocols = ["encore-ws"];
        if (headers) {
            protocols.push(encodeWebSocketHeaders(headers))
        }

        this.ws = new WebSocket(url, protocols)

        this.on("error", () => {
            this.resolveHasUpdateHandlers();
        });

        this.on("close", () => {
            this.resolveHasUpdateHandlers();
        });
    }

    resolveHasUpdateHandlers() {
        const handlers = this.hasUpdateHandlers;
        this.hasUpdateHandlers = [];

        for (const handler of handlers) {
            handler()
        }
    }

    async hasUpdate() {
        // await until a new message have been received, or the socket is closed
        await new Promise((resolve) => {
            this.hasUpdateHandlers.push(() => resolve(null))
        });
    }

    on(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.addEventListener(type, handler);
    }

    off(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.removeEventListener(type, handler);
    }

    close() {
        this.ws.close();
    }
}

export class StreamInOut<Request, Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamIn<Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamOut<Request, Response> {
    public socket: WebSocketConnection;
    private responseValue: Promise<Response>;

    constructor(url: string, headers?: Record<string, string>) {
        let responseResolver: (_: any) => void;
        this.responseValue = new Promise((resolve) => responseResolver = resolve);

        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            responseResolver(JSON.parse(event.data, dateReviver))
        });
    }

    async response(): Promise<Response> {
        return this.responseValue;
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}


// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(this);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {}

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (!BROWSER) {
            this.headers["User-Agent"] = "leave-management-system-99ki-Generated-TS-Client (Encore/v1.49.1)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }
    }

    async getAuthData(): Promise<CallParameters | undefined> {
        return undefined;
    }

    // createStreamInOut sets up a stream to a streaming API endpoint.
    async createStreamInOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamInOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamInOut(this.baseURL + path + queryString, headers);
    }

    // createStreamIn sets up a stream to a streaming API endpoint.
    async createStreamIn<Response>(path: string, params?: CallParameters): Promise<StreamIn<Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamIn(this.baseURL + path + queryString, headers);
    }

    // createStreamOut sets up a stream to a streaming API endpoint.
    async createStreamOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamOut(this.baseURL + path + queryString, headers);
    }

    // callTypedAPI makes an API call, defaulting content type to "application/json"
    public async callTypedAPI(path: string, params?: CallParameters): Promise<Response> {
        return this.callAPI(path, {
            ...params,
            headers: { "Content-Type": "application/json", ...params?.headers }
        });
    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(path: string, params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
        }

        // Merge our headers with any predefined headers
        init.headers = {...this.headers, ...init.headers, ...headers}

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                init.headers = {...init.headers, ...authData.headers};
            }
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        const response = await this.fetcher(this.baseURL+path+queryString, init)

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null &&
        isErrCode(err.code) &&
        typeof(err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof(err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);

        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value:        'APIError',
            enumerable:   false,
            configurable: true,
        })

        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) {
            (this as any).__proto__ = APIError.prototype
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }

        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}

export default new Client(import.meta.env.VITE_CLIENT_TARGET, { requestInit: { credentials: "include" } });
